name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'  # 使用你的 Go 版本

      - name: Download dependencies
        run: go mod download

      - name: Get version info
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Update version file
        run: |
          cat > internal/version/version.go << EOL
          package version

          var (
              Version = "${{ steps.get_version.outputs.VERSION }}"
              Commit  = "${{ steps.get_version.outputs.COMMIT }}"
              Date    = "${{ steps.get_version.outputs.DATE }}"
          )
          EOL

      - name: Build executables
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          COMMIT: ${{ steps.get_version.outputs.COMMIT }}
          DATE: ${{ steps.get_version.outputs.DATE }}
        run: |
          mkdir -p out
          GOOS=windows GOARCH=amd64 go build -o out/windows_amd64/easynovel.exe -ldflags="-X 'github.com/767829413/easy-novel/internal/version.Version=$VERSION' -X 'github.com/767829413/easy-novel/internal/version.Commit=$COMMIT' -X 'github.com/767829413/easy-novel/internal/version.Date=$DATE'" .
          GOOS=linux GOARCH=amd64 go build -o out/linux_amd64/easynovel -ldflags="-X 'github.com/767829413/easy-novel/internal/version.Version=$VERSION' -X 'github.com/767829413/easy-novel/internal/version.Commit=$COMMIT' -X 'github.com/767829413/easy-novel/internal/version.Date=$DATE'" .
          GOOS=darwin GOARCH=amd64 go build -o out/darwin_amd64/easynovel -ldflags="-X 'github.com/767829413/easy-novel/internal/version.Version=$VERSION' -X 'github.com/767829413/easy-novel/internal/version.Commit=$COMMIT' -X 'github.com/767829413/easy-novel/internal/version.Date=$DATE'" .

      - name: Compress executables
        run: |
          cd out/windows_amd64 && zip -r ../../easynovel-windows-amd64.zip . && cd ../..
          cd out/linux_amd64 && tar -czvf ../../easynovel-linux-amd64.tar.gz . && cd ../..
          cd out/darwin_amd64 && tar -czvf ../../easynovel-darwin-amd64.tar.gz . && cd ../..

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: --tag ${{ steps.get_version.outputs.VERSION }} --output CHANGELOG.md
        env:
          OUTPUT: CHANGELOG.md

      - name: Read CHANGELOG.md
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip,*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.changelog.outputs.content }}